import React from 'react'

export default function About() {
  return (
    <div className='container my-5' >
      <h1 style={{textAlign:"center"}}>About Us</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam nobis amet debitis fuga deleniti consequatur aut iste placeat excepturi sapiente. Omnis, ullam. Exercitationem nostrum, recusandae, tempore sint vero dolorem quaerat aspernatur, laboriosam fugiat voluptatibus labore! Enim sit eligendi aut rem asperiores quidem, nostrum animi officia. Accusamus sunt quibusdam animi dignissimos, repudiandae voluptatum aut eligendi voluptatibus perferendis expedita officiis, ab eveniet inventore velit culpa officia quisquam pariatur dicta cupiditate cum? Facere nihil ipsa officiis expedita fugiat, dolore harum nisi modi, illum quos aut aliquam, quidem id vitae quae. Fuga sunt earum vel recusandae aspernatur ad, pariatur at expedita facere architecto quisquam debitis laudantium adipisci, ex nostrum perspiciatis velit hic consectetur, cumque ut. Perferendis unde id voluptatum hic. Minus voluptates dolores fugiat incidunt corporis culpa suscipit sit totam odit, voluptatibus doloribus, maiores sequi labore eos nesciunt velit nulla dicta quaerat eum necessitatibus! Dicta asperiores ut corporis magnam amet, nesciunt veritatis dolorum molestiae, molestias hic saepe maxime, in quam at nobis numquam debitis! Facilis quisquam deleniti debitis magni pariatur odio earum officia, quaerat commodi nisi rerum? Omnis eveniet aliquam saepe, esse doloribus eos quibusdam, natus exercitationem nesciunt, animi praesentium. Quasi aspernatur voluptatibus placeat eum perferendis alias atque. Ullam eligendi, nemo rerum, suscipit optio sed reiciendis porro ea sit sunt adipisci molestiae labore quibusdam quia, veniam tempore? Perspiciatis ratione fugit modi tempora, voluptate voluptatibus eligendi ipsum et perferendis, earum, labore eius? Quis libero distinctio aut quos natus dolor ipsa odio sit nostrum aspernatur veritatis fugiat facere voluptate nulla cupiditate magni et ex rerum repellendus consequatur, aperiam omnis ratione. Maxime eaque sit odit accusantium facere quaerat, vel magnam accusamus quisquam quibusdam, ducimus vitae necessitatibus tempora nemo maiores suscipit esse harum iusto debitis quae! Optio, quaerat. Fugit nam ipsa, asperiores suscipit voluptatem molestias sit! Ipsa, perferendis magni provident molestias labore aut! Voluptas suscipit ducimus distinctio nemo? Dignissimos iure officia tempore labore nisi suscipit a minus aspernatur ipsam ipsum cupiditate, molestias quos explicabo sed necessitatibus porro, maxime magni, eum nesciunt. Minima vero similique aspernatur rem ducimus, inventore corrupti ipsa placeat obcaecati praesentium cupiditate? Numquam aut sit architecto totam est laboriosam labore recusandae maxime illo quod veritatis laudantium, libero ipsa a nesciunt officiis ut rem explicabo dolore ex, molestiae, magni tempora inventore dolorum.
      </p>
    </div>
  )
}
